=== jetify-com/devbox/.schema/devbox.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$id": "https://github.com/jetify-com/devbox",
    "title": "Devbox json definition",
    "description": "Defines fields and acceptable values of devbox.json",
    "type": "object",
    "properties": {
        "$schema": {
            "description": "The schema version of this devbox.json file.",
            "type": "string"
        },
        "name": {
            "description": "The name of the Devbox development environment.",
            "type": "string"
        },
        "description": {
            "description": "A description of the Devbox development environment.",
            "type": "string"
        },
        "packages": {
            "description": "Collection of packages to install",
            "oneOf": [
                {
                    "type": "array",
                    "items": {
                        "description": "Name and version of each package in name@version format.",
                        "type": "string"
                    }
                },
                {
                    "type": "object",
                    "description": "Name of each package in {\"name\": {\"version\": \"1.2.3\"}} format.",
                    "patternProperties": {
                        ".*": {
                            "oneOf": [
                                {
                                    "type": "object",
                                    "description": "Version number of the specified package in {\"version\": \"1.2.3\"} format.",
                                    "properties": {
                                        "version": {
                                            "type": "string",
                                            "description": "Version of the package"
                                        },
                                        "platforms": {
                                            "type": "array",
                                            "description": "Names of platforms to install the package on. This package will be skipped for any platforms not on this list",
                                            "items": {
                                                "enum": [
                                                    "i686-linux",
                                                    "aarch64-linux",
                                                    "aarch64-darwin",
                                                    "x86_64-darwin",
                                                    "x86_64-linux",
                                                    "armv7l-linux"
                                                ]
                                            }
                                        },
                                        "excluded_platforms": {
                                            "type": "array",
                                            "description": "Names of platforms to exclude the package on",
                                            "items": {
                                                "enum": [
                                                    "i686-linux",
                                                    "aarch64-linux",
                                                    "aarch64-darwin",
                                                    "x86_64-darwin",
                                                    "x86_64-linux",
                                                    "armv7l-linux"
                                                ]
                                            }
                                        },
                                        "glibc_patch": {
                                            "type": "boolean",
                                            "description": "Whether to patch glibc to the latest available version for this package"
                                        }
                                    }
                                },
                                {
                                    "type": "string",
                                    "description": "Version of the package to install."
                                }
                            ]
                        }
                    }
                }
            ]
        },
        "env": {
            "description": "List of additional environment variables to be set in the Devbox environment. Values containing $PATH or $PWD will be expanded. No other variable expansion or command substitution will occur.",
            "type": "object",
            "patternProperties": {
                ".*": {
                    "type": "string",
                    "description": "Value of the environment variable."
                }
            }
        },
        "init_hook": {
            "description": "List of shell commands/scripts to run right after devbox shell starts.",
            "type": [
                "array",
                "string"
            ],
            "items": {
                "type": "string"
            }
        },
        "scripts": {
            "description": "List of command/script definitions to run with `devbox run <script_name>`.",
            "type": "object",
            "patternProperties": {
                ".*": {
                    "description": "Alias name for the script.",
                    "type": [
                        "array",
                        "string"
                    ],
                    "items": {
                        "type": "string",
                        "description": "The script's shell commands."
                    }
                }
            }
        },
        "shell": {
            "deprecated": true,
            "description": "Deprecated: use the top-level init_hook and scripts fields instead. Run `devbox config fmt` to migrate.",
            "type": "object",
            "properties": {
                "init_hook": {
                    "type": [
                        "array",
                        "string"
                    ],
                    "items": {
                        "description": "List of shell commands/scripts to run right after devbox shell starts.",
                        "type": "string"
                    }
                },
                "scripts": {
                    "description": "List of command/script definitions to run with `devbox run <script_name>`.",
                    "type": "object",
                    "patternProperties": {
                        ".*": {
                            "description": "Alias name for the script.",
                            "type": [
                                "array",
                                "string"
                            ],
                            "items": {
                                "type": "string",
                                "description": "The script's shell commands."
                            }
                        }
                    }
                }
            },
            "additionalProperties": false
        },
        "aliases": {
            "description": "Shell aliases set up when entering the devbox shell, after the init_hook runs. Works in bash, zsh, and fish.",
            "type": "object",
            "patternProperties": {
                ".*": {
                    "description": "The command the alias expands to.",
                    "type": "string"
                }
            }
        },
        "include": {
            "description": "List of additional plugins to activate within your devbox shell",
            "type": "array",
            "items": {
                "description": "Name of the plugin to activate.",
                "type": "string"
            }
        },
        "env_from": {
            "type": "string"
        },
        "nixpkgs": {
            "type": "object",
            "properties": {
                "commit": {
                    "type": "string",
                    "description": "The commit hash of the nixpkgs repository to use"
                }
            }
        }
    },
    "additionalProperties": false
}

=== jetify-com/devbox/examples/cloud_development/minikube/devbox.json
{
    "packages": [
        "minikube",
        "kubectl",
        "kubernetes-helm-wrapped",
        "docker"
    ],
    "env": {
        "MINIKUBE_HOME": "$PWD/home/.minkube",
        "KUBECONFIG": "$PWD/home/.kube/config"
    },
    "shell": {
        "init_hook": [
            "helm repo add my-repo https://charts.bitnami.com/bitnami"
        ],
        "scripts": {
            "minikube": [
                "finish() { minikube stop; }",
                "trap finish SIGTERM SIGINT EXIT",
                "minikube start",
                "minikube logs -f"
            ]
        }
    },
    "nixpkgs": {
        "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
    }
}

=== jetify-com/devbox/examples/plugins/v2-local/plugin1/plugin1a/plugin.json
{
  "name": "plugin1a",
  "packages": ["cowsay@latest"],
  "env": {
    "PLUGIN1A_ENV": "success"
  },
  "shell": {
    "init_hook": [
      "export PLUGIN1A_INIT_HOOK=success"
    ],
    "scripts": {
      "plugin_1A_script": [
        "echo success"
      ]
    }
  },
  "include": [
    "../../plugin2"
  ]
}

=== jetify-com/devbox/examples/data_science/pytorch/basic-example/devbox.json
{
    "packages": [
        "python310",
        "poetry",
        "stdenv.cc.cc.lib",
        "cudatoolkit"
    ],
    "env": {
        "LD_LIBRARY_PATH": "$PWD/.devbox/nix/profile/default/lib:/usr/lib/wsl/lib"
    },
    "shell": {
        "init_hook": [],
        "scripts": {
            "install": "poetry install",
            "main": "poetry run python main.py"
        }
    },
    "nixpkgs": {
        "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
    }
}
