=== jetify-com/devbox/.schema/devbox-plugin.schema.json
{
  "$schema": "https://json-schema.org/draft-04/schema#",
  "$id": "https://github.com/jetpack-io/devbox/plugins",
  "title": "Devbox Plugin Schema",
  "description": "Defines fields and values for public devbox plugins",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "The schema version of this plugin file.",
      "type": "string"
    },
    "name": {
      "description": "The name of the plugin.",
      "type": "string"
    },
    "version": {
      "description": "The version of the plugin.",
      "type": "string"
    },
    "readme": {
      "description": "A short description of the plugin and how it works. This will automatically display when the user first installs the plugin, or runs `devbox info`",
      "type": "string"
    },
    "env": {
      "type": "object",
      "description": "List of additional environment variables to be set in the Devbox environment. These can be overridden by environment variables set in the user's devbox.json",
      "patternProperties": {
        ".*": {
          "type": "string",
          "description": "Value of the environment variable."
        }
      }
    },
    "create_files": {
      "type": "object",
      "description": "List of files to create in the user's project directory when the plugin is activated. The key points to the file path where the file will be created. The value points to the default file that should be copied to that location",
      "patternProperties": {
        ".*": {
          "type": "string",
          "description": "Contents of the file."
        }
      }
    },
    "shell": {
      "type": "object",
      "description": "Shell specific options and hooks for the plugin.",
      "items": {
        "init_hook": {
          "type": ["array", "string"],
          "description": "Shell command to run right before initializing the user's shell, running a script, or starting a service"
        }
      }
    }
  },
  "required": ["name", "version", "readme"]
}

=== jetify-com/devbox/plugins/pip.json
{
    "name": "pip",
    "version": "0.0.1",
    "readme": "This plugin adds a script for automatically creating a virtual environment using `venv` for python3 projects, so you can install packages with pip as normal.\nTo activate the environment, run `source $VENV_DIR/bin/activate` or add it to the init_hook of your devbox.json\nTo change where your virtual environment is created, modify the $VENV_DIR environment variable in your init_hook",
    "env": {
        "VENV_DIR": "{{ .Virtenv }}/.venv"
    },
    "create_files": {
        "{{ .Virtenv }}/bin/venvShellHook.sh": "pip/venvShellHook.sh"
    },
    "shell": {
        "init_hook": [
            "{{ .Virtenv }}/bin/venvShellHook.sh"
        ]
    }
}

=== jetify-com/devbox/plugins/nodejs.json
{
    "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/main/.schema/devbox-plugin.schema.json",
    "version": "0.0.2",
    "name": "nodejs",
    "readme": "Devbox automatically configures Corepack for Nodejs when DEVBOX_COREPACK_ENABLED=1. You can install Yarn or Pnpm by adding them to your `package.json` file using `packageManager`\nCorepack binaries will be installed in your local `.devbox` directory\n\nWhen Corepack is enabled, Devbox also activates the package manager pinned in your `package.json` `packageManager` field automatically. Set DEVBOX_DISABLE_NODEJS_PACKAGE_MANAGER_AUTODETECT=1 to disable this behavior.",
    "shell": {
        "init_hook": [
            "test -z \"${DEVBOX_COREPACK_ENABLED:-}\" || corepack enable --install-directory \"{{ .Virtenv }}/corepack-bin/\"",
            "test -z \"${DEVBOX_COREPACK_ENABLED:-}\" || export PATH=\"{{ .Virtenv }}/corepack-bin/:$PATH\"",
            "test -z \"${DEVBOX_COREPACK_ENABLED:-}\" || node \"{{ .Virtenv }}/bin/activate-package-manager.js\""
        ]
    },
    "create_files": {
      "{{ .Virtenv }}/corepack-bin": "",
      "{{ .Virtenv }}/bin/activate-package-manager.js": "nodejs/activate-package-manager.js"
    }
}

=== jetify-com/devbox/plugins/gradle.json
{
    "name": "gradle",
    "version": "0.0.1",
    "readme": "You can customize which JDK gradle will use by specifying the value of `org.gradle.java.home` in gradle.properties file",
    "shell": {
        "init_hook": [
            "[ -s gradle.properties ] || echo org.gradle.java.home=$JAVA_HOME >> gradle.properties"
        ]
    }
}

=== jetify-com/devbox/pkgcfg/package-configuration/apacheHttpd.json
{
  "name": "apache",
  "version": "0.0.1",
  "readme": "To start use \"apachectl start -f $HTTPD_CONFDIR/httpd.conf\".\n\nIf you with to edit the config file, please copy it out of the .devbox directory.",
  "env": {
    "HTTPD_CONFDIR": "{{ .DevboxRoot }}/conf/apache",
    "HTTPD_PORT": "8080"
  },
  "create_files": {
    ".devbox/conf/apache/httpd.conf": "apache/httpd.conf"
  }
}

=== jetify-com/devbox/pkgcfg/package-configuration/postgresql*.json
{
  "name": "postgresql",
  "version": "0.0.1",
  "readme": "To initialize the database, run `initdb`. To start the database, run `pg_ctl -l .devbox/conf/postgresql/logfile start`. To stop use `pg_ctl stop`.",
  "env": {
    "PGDATA": "{{ .DevboxRoot }}/conf/postgresql/data"
  },
  "create_files": {
    ".devbox/conf/postgresql/data": ""
  }
}

=== jetify-com/devbox/pkgcfg/package-configuration/nginx.json
{
  "name": "nginx",
  "version": "0.0.1",
  "readme": "To start nginx use command \"nginx\". nginx is configured to use .devbox/conf/nginx.conf. Use $NGINX_CONFDIR to change the configuration directory. Use $NGINX_LOGDIR to change the log directory. Use $NGINX_PIDDIR to change the pid directory. Use $NGINX_RUNDIR to change the run directory. Use $NGINX_SITESDIR to change the sites directory. Use $NGINX_TMPDIR to change the tmp directory. Use $NGINX_USER to change the user. Use $NGINX_GROUP to customize.",
  "env": {
    "NGINX_CONFDIR": "{{ .DevboxRoot }}/conf/nginx"
  },
  "create_files": {
    ".devbox/conf/nginx/temp": "",
    ".devbox/conf/nginx/nginx.conf": "nginx/nginx.conf",
    ".devbox/conf/nginx/fastcgi.conf": "nginx/fastcgi.conf",
    ".devbox/conf/nginx/bin/nginx": "nginx/nginx"
  }
}

=== jetify-com/devbox/examples/plugins/local/my-plugin/my-plugin.json
{
  "name": "my-plugin",
  "version": "0.0.1",
  "readme": "Example custom plugin",
  "env": {
    "MY_FOO_VAR": "BAR"
  },
  "create_files": {
    "{{ .Virtenv }}/empty-dir": "",
    "{{ .Virtenv }}/some-file": "some-file.txt",
    "{{ .DevboxDir }}/some-file.txt": "some-file.txt",
    "{{ .Virtenv }}/process-compose.yaml": "process-compose.yaml"
  },
  "shell": {
      "init_hook": [
          "export MY_INIT_HOOK_VAR=BAR"
      ]
  }
}
